In [31]:
import numpy as np

Arrays:

In [10]:
my_list = [1,2,3]

In [12]:
arr = np.array(my_list)

In [13]:
print(arr)

[1 2 3]


In [14]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]

In [15]:
mat = np.array(my_mat)

In [16]:
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [19]:
np.zeros(4)

array([ 0.,  0.,  0.,  0.])

In [23]:
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [24]:
np.linspace(0,5,10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [30]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

Random:

In [26]:
np.random.rand(5)

array([ 0.58024797,  0.29449561,  0.66258603,  0.43607606,  0.16013298])

In [27]:
np.random.rand(3,3)

array([[ 0.7022863 ,  0.43134762,  0.43283461],
       [ 0.24573077,  0.69636615,  0.73603256],
       [ 0.10146593,  0.13032109,  0.2064001 ]])

In [28]:
np.random.randn(5)

array([-0.17879132, -0.11630873, -0.01587731,  1.16153417, -1.31581059])

In [29]:
np.random.randint(1, 100, 10)

array([84, 84, 15, 71,  7, 12, 43, 12, 13, 52])

In [43]:
arr = np.arange(25)

In [44]:
ranarr = np.random.randint(0,50,10)

In [45]:
print(arr)
arr = arr.reshape(5,5)
print(arr)
print(arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
(5, 5)


In [46]:
print(ranarr)
print(ranarr.max())
print(ranarr.argmax())

[24 24  4 48 16 15 13  9  0  8]
48
3
