In [1]:
import numpy as np

Selecting from an array:

In [4]:
arr = np.arange(0, 11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [6]:
print(arr[0])

0


In [9]:
slice_of_arr = arr[1:5]
print(slice_of_arr)

[1 2 3 4]


In [12]:
slice_of_arr[:] = 99
print(slice_of_arr)

[99 99 99 99]


In [13]:
print(arr)

[ 0 99 99 99 99  5  6  7  8  9 10]


In [14]:
arr_copy = arr.copy()
arr_copy[:] = 2
print(arr_copy)

[2 2 2 2 2 2 2 2 2 2 2]


Matrices:

In [15]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])
print(arr_2d)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [17]:
print(arr_2d[1][1])
print(arr_2d[1,1])

25
25


In [18]:
print(arr_2d[:2,1:])

[[10 15]
 [25 30]]


In [21]:
arr = np.arange(1,11)
print(arr)
bool_arr = arr > 5
print(bool_arr)

[ 1  2  3  4  5  6  7  8  9 10]
[False False False False False  True  True  True  True  True]


In [23]:
print(arr[bool_arr])

[ 6  7  8  9 10]


In [25]:
print(arr[arr > 5])

[ 6  7  8  9 10]
