In [1]:
import numpy as np

Array with Array:

In [2]:
arr = np.arange(0,11)

In [5]:
print(arr + arr)
print(arr - arr)
print(arr * arr)

[ 0  2  4  6  8 10 12 14 16 18 20]
[0 0 0 0 0 0 0 0 0 0 0]
[  0   1   4   9  16  25  36  49  64  81 100]


Scalar operations:

In [8]:
print(arr + 100)
print(arr / 100)

[100 101 102 103 104 105 106 107 108 109 110]
[ 0.    0.01  0.02  0.03  0.04  0.05  0.06  0.07  0.08  0.09  0.1 ]


Universal functions:

In [10]:
print(np.sqrt(arr))

[ 0.          1.          1.41421356  1.73205081  2.          2.23606798
  2.44948974  2.64575131  2.82842712  3.          3.16227766]
